go:
  - stl-verify/**
  - '!stl-verify/python/**'
  - '!stl-verify/ts/**'
  - lefthook.yml
  - stl-verify/lefthook.yml
  - stl-verify/python/lefthook.yml
  - stl-verify/ts/lefthook.yml
  - .github/changed-files.yml
  - .github/workflows/ci.yml
  - .github/workflows/deploy.yaml
  - .github/workflows/go-ci.yml

python:
  - stl-verify/python/**
  - stl-verify/db/migrations/**
  - lefthook.yml
  - stl-verify/lefthook.yml
  - stl-verify/python/lefthook.yml
  - .github/changed-files.yml
  - .github/workflows/ci.yml
  - .github/workflows/deploy.yaml
  - .github/workflows/python-ci.yml

ts:
  - stl-verify/ts/**
  - stl-verify/python/app/**
  - stl-verify/python/scripts/export_openapi_schema.py
  - stl-verify/python/Makefile
  - lefthook.yml
  - stl-verify/lefthook.yml
  - stl-verify/ts/lefthook.yml
  - .github/changed-files.yml
  - .github/workflows/ci.yml
  - .github/workflows/deploy.yaml
  - .github/workflows/ts-ci.yml
