// Package main generates Kubernetes Deployment manifests for all cronjobs
// discovered under cmd/cronjobs/. Each cronjob gets its own YAML file
// written to the output directory, suitable for committing to source control.
//
// Usage:
//
//	go run ./cmd/util/cronjob-manifest
//	go run ./cmd/util/cronjob-manifest --image-tag v1.2.3 --out k8s/apps/cronjobs
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

func main() {
	imageTag := flag.String("image-tag", "local", "Docker image tag (e.g. 'local', 'v1.2.3', commit SHA)")
	cronjobDir := flag.String("dir", "cmd/cronjobs", "Path to the cronjobs directory")
	outDir := flag.String("out", "k8s/apps/cronjobs", "Output directory for generated manifests")
	flag.Parse()

	names, err := discoverCronjobs(*cronjobDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error discovering cronjobs: %v\n", err)
		os.Exit(1)
	}

	if len(names) == 0 {
		fmt.Fprintf(os.Stderr, "no cronjobs found in %s\n", *cronjobDir)
		os.Exit(1)
	}

	if err := generateManifests(names, *imageTag, *outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error generating manifests: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "generated %d manifest(s) in %s\n", len(names), *outDir)
}

func discoverCronjobs(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", dir, err)
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		mainFile := filepath.Join(dir, e.Name(), "main.go")
		if _, err := os.Stat(mainFile); err == nil {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	return names, nil
}

const header = "# Generated by: go run ./cmd/util/cronjob-manifest\n# Do not edit manually.\n"

const deploymentTemplate = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      containers:
        - name: {{.Name}}
          image: stl-{{.Name}}:{{.ImageTag}}
          imagePullPolicy: {{.ImagePullPolicy}}
          envFrom:
            - configMapRef:
                name: stl-config
            - secretRef:
                name: stl-secrets
`

type templateData struct {
	Name            string
	ImageTag        string
	ImagePullPolicy string
}

func generateManifests(names []string, imageTag, outDir string) error {
	tmpl, err := template.New("deployment").Parse(deploymentTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	pullPolicy := "IfNotPresent"
	if imageTag == "local" {
		pullPolicy = "Never"
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Remove stale manifests for cronjobs that no longer exist.
	if err := removeStaleManifests(outDir, names); err != nil {
		return fmt.Errorf("cleaning stale manifests: %w", err)
	}

	for _, name := range names {
		var buf strings.Builder
		buf.WriteString(header)
		if err := tmpl.Execute(&buf, templateData{
			Name:            name,
			ImageTag:        imageTag,
			ImagePullPolicy: pullPolicy,
		}); err != nil {
			return fmt.Errorf("rendering %s: %w", name, err)
		}

		outPath := filepath.Join(outDir, name+".yaml")
		if err := os.WriteFile(outPath, []byte(buf.String()), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", outPath, err)
		}
	}

	return nil
}

// removeStaleManifests deletes .yaml files in outDir that don't correspond
// to any discovered cronjob name.
func removeStaleManifests(outDir string, validNames []string) error {
	valid := make(map[string]bool, len(validNames))
	for _, n := range validNames {
		valid[n+".yaml"] = true
	}

	entries, err := os.ReadDir(outDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		if !valid[e.Name()] {
			if err := os.Remove(filepath.Join(outDir, e.Name())); err != nil {
				return err
			}
		}
	}

	return nil
}
