apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-oracle-price-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanche-oracle-price-worker
  template:
    metadata:
      labels:
        app: avalanche-oracle-price-worker
    spec:
      containers:
        - name: avalanche-oracle-price-worker
          image: stl-oracle-price-worker:local
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: stl-config
            - secretRef:
                name: stl-secrets
          env:
            - name: CHAIN_ID
              value: "43114"
            - name: ALCHEMY_HTTP_URL
              value: https://avax-mainnet.g.alchemy.com/v2
            - name: AWS_SQS_QUEUE_URL
              value: http://localstack:4566/000000000000/stl-avalanche-oracle-price.fifo
