apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche-backup-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanche-backup-worker
  template:
    metadata:
      labels:
        app: avalanche-backup-worker
    spec:
      serviceAccountName: avalanche-backup-worker
      containers:
        - name: avalanche-backup-worker
          image: avalanche-backup-worker
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: JAEGER_ENDPOINT
              value: "localhost:4317"
          envFrom:
            - configMapRef:
                name: avalanche-backup-worker-config
            - secretRef:
                name: avalanche-backup-worker
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep -f raw_data_backup"]
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
      terminationGracePeriodSeconds: 60
