apiVersion: apps/v1
kind: Deployment
metadata:
  name: maple-graphql-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maple-graphql-indexer
  template:
    metadata:
      labels:
        app: maple-graphql-indexer
    spec:
      serviceAccountName: maple-graphql-indexer
      containers:
        - name: maple-graphql-indexer
          image: maple-graphql-indexer
          envFrom:
            - configMapRef:
                name: maple-graphql-indexer
            - secretRef:
                name: maple-graphql-indexer
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      terminationGracePeriodSeconds: 60
