-- Migrations are immutable, so correcting the create migration's "incomplete by
-- construction" coverage claim takes a new COMMENT ON rather than an edit. Only
-- the coverage sentence changes; every other sentence is the create migration's.

COMMENT ON TABLE uniswap_v4_position IS
  '[Operational] Append-on-change authoritative per-position state from StateView.getPositionInfo(poolId, owner, tickLower, tickUpper, salt) reads. A new row is written only when the read-back state differs from the latest stored row for the natural key (pool_id, owner, tick_lower, tick_upper, salt), or when block_version differs at the same height (a reorg re-observation of one block always appends; a later block with identical values does not). Two writers share that getter, block-hash pin and write path, so a row from either is byte-identical for the same block. (1) The live indexer, per block, for every position that block''s ModifyLiquidity events touched -- event-driven, and therefore incomplete on its own: V4 exposes no way to enumerate a pool''s positions, so a position minted before the indexer went live and never touched since would never appear. (2) The one-shot uniswap-v4-position-bootstrap backfiller (VEC-639), which closes that hole by replaying the PoolManager''s whole ModifyLiquidity history for the registered snapshot_supported pools and snapshotting every key it finds at ONE pinned block -- by default head minus 64 (past finality, hence block_version 0 and no reorg versioning); a pin inside the reorg window is refused. Its rows therefore share a single block_number across pools, and are superseded naturally by later live touches. It is idempotent and keeps no progress state: a rerun over covered history appends nothing, because the append-on-change read is bounded to rows at or below the pin and so cannot regress a newer live row. A position''s state before the earliest row here is still unknown. Carries no token amounts -- V4 stores only liquidity and the two fee-growth checkpoints, so amounts are a downstream derivation from liquidity, the pool''s sqrt_price_x96 and the tick bounds. Append-only via the processing_version trigger. Deliberately a plain table, not a hypertable, under the append-on-change exception in db/migrations/AGENTS.md and for the same reason as uniswap_v4_tick: every write first reads the latest row per natural key at or below a block height, and that read admits no block_timestamp bound -- the height bound is load-bearing for out-of-order backfill writes, and a position can sit untouched arbitrarily long -- so a block_timestamp-partitioned hypertable would prune no chunks on the per-block path (VEC-541), and S3 tiering would go further and hide the prior row from the change comparison (timescaledb.enable_tiered_reads defaults off), making the writer append a change that never happened. Unbounded row growth is the price, covered by the VectorUniswapV4AppendOnChangeGrowthHigh row-growth alert and the conversion path in the indexer runbook rather than by compression; a converted table must carry no tiering policy, or bound the comparison read''s lookback below the tiering horizon, or that wrong-data failure returns.';

INSERT INTO migrations (filename)
VALUES ('20260910_130000_uniswap_v4_position_bootstrap_comment.sql')
ON CONFLICT (filename) DO NOTHING;
