-- Migrations are immutable, so correcting the create migration's "incomplete by
-- construction" coverage claim takes a new COMMENT ON rather than an edit.

COMMENT ON TABLE uniswap_v4_position IS
  '[Operational] Append-on-change authoritative per-position state from StateView.getPositionInfo(poolId, owner, tickLower, tickUpper, salt) reads. A new row is written only when the read-back state differs from the latest stored row for the natural key (pool_id, owner, tick_lower, tick_upper, salt), or when block_version differs (a reorg re-observation always appends). Rows come from two writers that share one getter, one block-hash pin and one write path, so a row from either is byte-identical for the same block. (1) The live indexer, per block, for every position that block''s ModifyLiquidity events touched -- event-driven, and therefore incomplete on its own: V4 exposes no way to enumerate a pool''s positions, so a position minted before the indexer went live and never touched since would never appear. (2) The one-shot uniswap-v4-position-bootstrap backfiller (VEC-639), which closes that hole by replaying the PoolManager''s whole ModifyLiquidity history for the registered snapshot_supported pools and snapshotting every key it finds at ONE pinned block -- by default head minus 64 (past finality, hence block_version 0 and no reorg versioning); a pin inside the reorg window is refused. Its rows therefore share a single block_number across pools, and are superseded naturally by later live touches. It is idempotent and keeps no progress state: a rerun over covered history appends nothing, because the append-on-change read is bounded to rows at or below the pin and so cannot regress a newer live row. Coverage below a pool''s first bootstrap run is still open: a position''s state BEFORE the earliest row here is unknown. Carries no token amounts -- V4 stores only liquidity and the two fee-growth checkpoints, so amounts are a downstream derivation from liquidity, the pool''s sqrt_price_x96 and the tick bounds. Append-only via the processing_version trigger. NOT a hypertable, deliberately, for the same reason as its sibling uniswap_v4_tick: rows are written on-change rather than on every touched block, and each write first reads the latest row per natural key with no time bound the planner could use, so partitioning would turn one bounded index lookup into a fan-out over every chunk (the cost profile ADR-0002/VEC-541 describes) while buying nothing a plain index does not already give.';

INSERT INTO migrations (filename)
VALUES ('20260824_120000_uniswap_v4_position_bootstrap_comment.sql')
ON CONFLICT (filename) DO NOTHING;
