apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparklend-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparklend-position-tracker
  template:
    metadata:
      labels:
        app: sparklend-position-tracker
    spec:
      serviceAccountName: sparklend-position-tracker
      containers:
        - name: sparklend-position-tracker
          image: sparklend-position-tracker
          envFrom:
            - secretRef:
                name: sparklend-position-tracker
          resources:
            requests:
              cpu: "1000m"
              memory: "2048Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep -f sparklend"]
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
      terminationGracePeriodSeconds: 60
